### ISSUE TITLE
How to change custom class

### ISSUE THREAD

**Issue by ferhatbesler** [han109k/light-switch#4]
Hi mate, how to change custom class?

Sample class:

.test10
.test10-dark

**Comment by han109k** [comment]
```
/* CSS */
.custom-theme.bg-light {
  background-color: darkslategray !important;
  color: gainsboro;
  text-decoration: underline;
}

.custom-theme.bg-dark {
  background-color: blanchedalmond !important;
  color: dimgray;
  text-decoration: overline;
}

<-- HTML !-->
<div class="card-body custom-theme bg-light">
    This is component has a custom class applied to it.
</div>
```
For now, you can do it like this. Don't forget to add **!important** tag for background color. Also, you can customize Bootstrap's default theme: [Bootstrap Sass](https://getbootstrap.com/docs/5.1/customize/sass/#file-structure)
