### ISSUE TITLE
Nav-link items

### ISSUE THREAD

**Issue by Depechie** [han109k/light-switch#5]
I'm having trouble using the switch js together with nav-links.
Example: [https://getbootstrap.com/docs/5.0/examples/sidebars/](https://getbootstrap.com/docs/5.0/examples/sidebars/)

There is `class="nav-link link-dark"` and `class="nav-link text-white"`.

Bit weird they have 2 different class items for the nav text.

**Comment by han109k** [comment]
Thanks for the heads up. I'll fix it asap.

**Comment by Depechie** [comment]
There is also a https://bootstrapshuffle.com/classes/colors/link-light !
Did not notice this, so still wondering if they created the demo wrong!
